kind: pipeline
type: kubernetes
name: Devpunk

steps:
  - name: build
    image: plugins/docker
    repo: reezpatel/devpunk
    tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
