kind: pipeline
name: Devpunk

steps:
  - name: build
    image: plugins/docker
    repo: reezpatel/devpunk
    tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
      