kind: pipeline
type: kubernetes
name: Devpunk

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: reezpatel/devpunk
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:6}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
  - name: install
    image: alpine/helm:3.2.1
    commands:
      - ls
      - pwd
