kind: pipeline
type: kubernetes
name: Devpunk

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: reezpatel/devpunk
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:6}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
  - name: install
    image: alpine/helm:3.2.1
    commands:
      - echo "${KUBECONFIG_FILE}" > kubeconfig.yml
      - export KUBECONFIG="$PWD/kubeconfig.yml"
      - cd deployment/devpunk-server
      - helm upgrade --wait --set-string image.tag="${DRONE_COMMIT_SHA:0:6}" devpunk . -n feeds
      - rm "$KUBECONFIG"
  - name: ui
    image: andreysenov/firebase-tools
    commands:
      - npm install
      - yarn exec nx build devpunk-react
      - firebase deploy --token "${FIREBASE_TOKEN}"
