kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker
    commands:
      - docker build -t reezpatel/devpunk:latest -t "reezpatel/devpunk${DRONE_COMMIT_SHA:0:8}" .
      - docker login --username reezpatel --password a2d8cd84-74ed-4188-bdbc-e6bab999acfd
      - docker push reezpatel/devpunk:latest
