apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "devpunk-server.fullname" . }}
  labels:
    app: {{ template "devpunk-server.name" . }}
    chart: {{ template "devpunk-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    linkerd.io/inject: enabled
    rollme: {{ randAlphaNum 5 | quote }}
{{ toYaml .Values.annotations | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "devpunk-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: {{ template "devpunk-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: "/usr/share/devpunk"
              name: devpunk-volume
          envFrom:
            - configMapRef:
                name: {{ template "devpunk-server.name" . }}-config
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1
              port: 3333
          readinessProbe:
            httpGet:
              path: /v1
              port: 3333
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: devpunk-volume
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "devpunk-server.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
