name: CI

on:
  push:
    branches: [master]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Docker Publish
  #       uses: manusa/actions-publish-docker@v1.0.1
  #       with:
  #         name: reezpatel/devpunk
  #         tag: latest
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          echo $KUBECONFIG_FILE > kubeconfig.yml   
          export KUBECONFIG="$KUBECONFIG_FILE/kubeconfig.yml"
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
      - name: Deploy
        run: |
          helm ls
          cd deployment/devpunk-server
          helm upgrade devpunk .
      - name: Cleaup
        run: rm "$KUBECONFIG"
