name: Server

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      - name: Docker Publish
        uses: manusa/actions-publish-docker@v1.0.1
        with:
          name: reezpatel/devpunk
          tag: ${{ steps.vars.outputs.sha_short }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "$KUBECONFIG_FILE" > kubeconfig.yml   
          export KUBECONFIG="$PWD/kubeconfig.yml"
          cd deployment/devpunk-server
          helm upgrade --wait --install --set-string image.tag="${{ steps.vars.outputs.sha_short }}" devpunk . -n feeds
          rm "$KUBECONFIG"
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
