name: Server

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Publish
        uses: manusa/actions-publish-docker@v1.0.1
        with:
          name: reezpatel/devpunk
          tag: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "$KUBECONFIG_FILE" > kubeconfig.yml   
          export KUBECONFIG="$PWD/kubeconfig.yml"
          cd deployment/devpunk-server
          helm delete devpunk
          helm upgrade --force -i --wait devpunk .
          rm "$KUBECONFIG"
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
