name: Web UI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build
        run: |
          npm install
          yarn exec nx build devpunk-react
      - name: Deploy
        run: |
          npm i -g firebase-tools
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
